TOP = ../..
include $(TOP)/configure/CONFIG

SCRIPTS+=stexample.boot
SCRIPTS+=st3jackexample.boot
SCRIPTS+=stHomingExample.boot
SCRIPTS+=stPosCompEx.boot
SCRIPTS+=stCompensationTable.boot

include $(TOP)/configure/RULES
